INFO 09-11 15:27:03 [__init__.py:241] Automatically detected platform cuda.
INFO 09-11 15:27:04 [utils.py:326] non-default args: {'model': '/home/minyingqian/models/Qwen2.5-7B-Instruct', 'trust_remote_code': True, 'disable_log_stats': True}
The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
INFO 09-11 15:27:11 [__init__.py:711] Resolved architecture: Qwen2ForCausalLM
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 09-11 15:27:11 [__init__.py:1750] Using max model len 32768
INFO 09-11 15:27:11 [scheduler.py:222] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 09-11 15:27:16 [__init__.py:241] Automatically detected platform cuda.
[1;36m(EngineCore_0 pid=2556998)[0;0m INFO 09-11 15:27:18 [core.py:636] Waiting for init message from front-end.
[1;36m(EngineCore_0 pid=2556998)[0;0m INFO 09-11 15:27:18 [core.py:74] Initializing a V1 LLM engine (v0.10.1.1) with config: model='/home/minyingqian/models/Qwen2.5-7B-Instruct', speculative_config=None, tokenizer='/home/minyingqian/models/Qwen2.5-7B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/home/minyingqian/models/Qwen2.5-7B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":[],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2"],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700] EngineCore failed to start.
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700] Traceback (most recent call last):
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     self._init_executor()
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700]     raise ValueError(
[1;36m(EngineCore_0 pid=2556998)[0;0m ERROR 09-11 15:27:20 [core.py:700] ValueError: Free memory on device (1.14/23.68 GiB) on startup is less than desired GPU memory utilization (0.9, 21.32 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
[1;36m(EngineCore_0 pid=2556998)[0;0m Process EngineCore_0:
[1;36m(EngineCore_0 pid=2556998)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_0 pid=2556998)[0;0m     self.run()
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_0 pid=2556998)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 704, in run_engine_core
[1;36m(EngineCore_0 pid=2556998)[0;0m     raise e
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 691, in run_engine_core
[1;36m(EngineCore_0 pid=2556998)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 492, in __init__
[1;36m(EngineCore_0 pid=2556998)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core.py", line 80, in __init__
[1;36m(EngineCore_0 pid=2556998)[0;0m     self.model_executor = executor_class(vllm_config)
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/executor/executor_base.py", line 54, in __init__
[1;36m(EngineCore_0 pid=2556998)[0;0m     self._init_executor()
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 48, in _init_executor
[1;36m(EngineCore_0 pid=2556998)[0;0m     self.collective_rpc("init_device")
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/executor/uniproc_executor.py", line 58, in collective_rpc
[1;36m(EngineCore_0 pid=2556998)[0;0m     answer = run_method(self.driver_worker, method, args, kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/utils/__init__.py", line 3007, in run_method
[1;36m(EngineCore_0 pid=2556998)[0;0m     return func(*args, **kwargs)
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/worker/worker_base.py", line 603, in init_device
[1;36m(EngineCore_0 pid=2556998)[0;0m     self.worker.init_device()  # type: ignore
[1;36m(EngineCore_0 pid=2556998)[0;0m   File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/worker/gpu_worker.py", line 179, in init_device
[1;36m(EngineCore_0 pid=2556998)[0;0m     raise ValueError(
[1;36m(EngineCore_0 pid=2556998)[0;0m ValueError: Free memory on device (1.14/23.68 GiB) on startup is less than desired GPU memory utilization (0.9, 21.32 GiB). Decrease GPU memory utilization or reduce GPU memory used by other processes.
Traceback (most recent call last):
  File "/home/minyingqian/vprm/MathVista/extract_answer.py", line 89, in <module>
    llm = LLM(
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 285, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 490, in from_engine_args
    return engine_cls.from_vllm_config(
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 127, in from_vllm_config
    return cls(vllm_config=vllm_config,
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/llm_engine.py", line 104, in __init__
    self.engine_core = EngineCoreClient.make_client(
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 80, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 600, in __init__
    super().__init__(
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/core_client.py", line 446, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/utils.py", line 706, in launch_core_engines
    wait_for_engine_startup(
  File "/home/minyingqian/anaconda3/envs/llmeval/lib/python3.10/site-packages/vllm/v1/engine/utils.py", line 759, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
